"""Session table created

Revision ID: 6b90de1b7dd0
Revises: eff2fd667de6
Create Date: 2025-01-11 15:41:26.845148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6b90de1b7dd0'
down_revision: Union[str, None] = 'eff2fd667de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['secure.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id'),
    schema='secure'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session', schema='secure')
    # ### end Alembic commands ###
