"""public and private key length updated

Revision ID: 929b9cbcfe7e
Revises: 966669c93ab0
Create Date: 2025-01-06 14:26:06.250749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '929b9cbcfe7e'
down_revision: Union[str, None] = '966669c93ab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('application', 'public_key',
                    type_=sa.VARCHAR(length=5000),
                    existing_type=sa.VARCHAR(length=255),
                    schema='secure')
    op.alter_column('application', 'private_key',
                    type_=sa.VARCHAR(length=5000),
                    existing_type=sa.VARCHAR(length=255),
                    schema='secure')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'public_key',
                    type_=sa.VARCHAR(length=255),
                    existing_type=sa.VARCHAR(length=5000),
                    schema='secure')
    op.alter_column('application', 'private_key',
                    type_=sa.VARCHAR(length=255),
                    existing_type=sa.VARCHAR(length=5000),
                    schema='secure')
    # ### end Alembic commands ###
