"""schema name added

Revision ID: 966669c93ab0
Revises: f21cec6fd455
Create Date: 2025-01-03 16:48:11.317183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '966669c93ab0'
down_revision: Union[str, None] = 'f21cec6fd455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='secure'
    )
    op.create_index(op.f('ix_secure_client_domain'), 'client', ['domain'], unique=False, schema='secure')
    op.create_table('user',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='secure'
    )
    op.create_table('application',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.BIGINT(), nullable=False),
    sa.Column('domain', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('application_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('application_secret', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('public_key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('private_key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['secure.client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='secure'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application', schema='secure')
    op.drop_table('user', schema='secure')
    op.drop_index(op.f('ix_secure_client_domain'), table_name='client', schema='secure')
    op.drop_table('client', schema='secure')
    # ### end Alembic commands ###
