"""authcode table created

Revision ID: eff2fd667de6
Revises: 929b9cbcfe7e
Create Date: 2025-01-06 17:11:18.145761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eff2fd667de6'
down_revision: Union[str, None] = '929b9cbcfe7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorisation_code',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['secure.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='secure'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorisation_code', schema='secure')
    # ### end Alembic commands ###
