class ErrorMessages:
  """ Error messages """
  EMAIL_ALREADY_EXISTS = "User with given email already exists!"
  APPLICATION_ALREADY_EXISTS = "Application with given domain already exists!"
  APPLICATION_NOT_A_SUBDOMAIN = "Application domain should be a valid subdomain!"
  NO_USER_WITH_GIVEN_EMAIL_EXITS = "No account for the given email exists!"
  NO_APPLICATION_WITH_GIVEN_ID_OR_SECRET_EXITS = "No application for the given id and secret exists!"
  NO_APPLICATION_WITH_GIVEN_ID_EXITS = "No application for the given id exists!"
  INCORRECT_PASSWORD = "Incorrect Password!"
  AUTHORISATION_CODE_EXPIRED = "Authorisation code has expired!"
  TOKEN_HAS_EXPIRED = "Token has expired!"
  INVALID_TOKEN = "Not a valid token!"